image: node

cache:
  paths:
    - node_modules/

before_script:
 - apt-get update -qq && apt-get install -y -qq sshpass

build prod:
  image: node:12.16.2-stretch
  stage: build
  only:
    - master
  script:
    - cp .env.production .env
    - rm -rf .env.*
    - yarn global add @vue/cli@latest
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
    
build stage:
  image: node:12.16.2-stretch
  stage: build
  only:
    - master
  script:
    - cp .env.staging .env
    - rm -rf .env.*
    - yarn global add @vue/cli@latest
    - yarn install
    - ls -la .env*
    - cat .env
    - yarn build
    - ls -la
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
    
deploy_stage:
  image: alpine
  stage: deploy
  only:
    - master
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ deployer@34.236.8.51:/var/www/influu/stg-influu.me/app/dist
  dependencies: 
    - build stage
  environment: 
    name: Staging
    url: https://staging.influu.me
  when: on_success
    
deploy_prod:
  image: alpine
  stage: deploy
  only:
    - master
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ deployer@34.236.8.51:/var/www/influu/influu.me/app/dist
  dependencies: 
    - build prod
  environment:
    name: production
    url: https://influu.me
  when: manual
