mutation updateInfluencerCampaignInvoice($input: UpdateInfluencerCampaignInvoiceInput!) {
  updateInfluencerCampaignInvoice(input: $input) {
    id
    status
    invoice {
    	id
    	status
    	attachment {
    		filename
    		url
    	}
    }
  }
}