mutation updateInfluencerDeliveryFromBacklogToValidation($input: UpdateInfluencerDeliveryFromBacklogToValidationInput!) {
  updateInfluencerDeliveryFromBacklogToValidation(input: $input) { 
    id
  }
}